plugins:
  bm_discourse_automation_enabled:
    default: false
    client: true
  bm_archive_category_map:
    type: objects
    default: []
    schema:
      name: category_archive_mapping
      properties:
        source_category:
          type: category
          required: true
        archive_category:
          type: category
          required: true
